version: '3.8'
services:
  api:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    #ports:
    #  - 8082:8082
    depends_on:
      - postgres
      - mongo
    network_mode: host
  postgres:
    image: postgres:16
    #ports:
     # - 5432:5432
    network_mode: host
    environment:
      POSTGRES_DB: "practic3employees"
      POSTGRES_USER: "root1"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
  mongo:
    image: mongo
    #ports:
    #  - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "practic3Adminki"
    network_mode: host

networks:
  host:
   external: true
    